// @generated by handbook/bin/gen-related-tools.mjs from handbook/tools.json — DO NOT EDIT.
// To change this tool's related-tools section, edit tools.json (this tool's `related[]`, or the
// referenced tools' hub.icon/hub.card), then run `node handbook/bin/gen-related-tools.mjs unlock-xlsx`
// (or with no arg to regenerate every active tool) and commit the result.

export interface RelatedToolCard {
  slug: string;
  icon: string;
  name: Record<string, string>;
  desc: Record<string, string>;
}

/** Curated related tools (Issue #177) — same hub.group baseline + genuine cross-group workflow ties. */
export const RELATED_TOOLS: RelatedToolCard[] = [
  {
    "slug": "strip-xlsx-metadata",
    "icon": "🧹",
    "name": {
      "en": "Strip XLSX Metadata",
      "ja": "Excelメタデータ削除",
      "zh": "清除 Excel 元数据",
      "de": "XLSX-Metadaten entfernen",
      "es": "Eliminar metadatos de XLSX"
    },
    "desc": {
      "en": "Remove author, company, and custom-property metadata from an Excel workbook.",
      "ja": "Excelブックの作成者・会社名・カスタムプロパティを削除。",
      "zh": "移除 Excel 工作簿中的作者、公司和自定义属性等元数据。",
      "de": "Entfernt Autor-, Firmen- und benutzerdefinierte Metadaten aus einer Excel-Arbeitsmappe.",
      "es": "Elimina el autor, la empresa y las propiedades personalizadas de un libro de Excel."
    }
  },
  {
    "slug": "xlsx-viewer",
    "icon": "📗",
    "name": {
      "en": "Excel Workbook Viewer",
      "ja": "Excelビューア",
      "zh": "Excel 查看器",
      "de": "Excel-Arbeitsmappen-Viewer",
      "es": "Visor de libros de Excel"
    },
    "desc": {
      "en": "Open and browse an Excel workbook: switch sheets, no editing.",
      "ja": "Excelブックを開いて閲覧。シート切替、編集はしません。",
      "zh": "打开并浏览 Excel 工作簿，可切换工作表，不支持编辑。",
      "de": "Excel-Arbeitsmappe öffnen und ansehen, Blätter wechseln, keine Bearbeitung.",
      "es": "Abre y consulta un libro de Excel, cambia de hoja, sin edición."
    }
  },
  {
    "slug": "unlock-zip",
    "icon": "🔓",
    "name": {
      "en": "Unlock ZIP",
      "ja": "Zipパスワード解除",
      "zh": "解锁 ZIP",
      "de": "ZIP entsperren",
      "es": "Desbloquear ZIP"
    },
    "desc": {
      "en": "Remove the password from a .zip you can open.",
      "ja": "開けるパスワード付き .zip のパスワードを解除。",
      "zh": "移除你能打开的 .zip 的密码。",
      "de": "Das Passwort aus einem .zip entfernen, das du öffnen kannst.",
      "es": "Quita la contraseña de un .zip que puedas abrir."
    }
  }
];

/** This tool's own engineering-notes article slug (/blog/<slug>/), or null if none is published yet. */
export const BLOG_SLUG: string | null = 'unlock-xlsx';
